[tool.poetry]
name = "novelconverter"
version = "5.0.0.dev0"
description = "Convert syntax for multiple Web-Novel sites."
authors = ["Ray Shirohara <RShirohara@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
black = "*"
flake8 = "*"
mypy = "*"

[tool.poetry.scripts]
novelconv = 'novelconv.cli:main'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
